### PR TITLE
Speedup lexers

### PR DESCRIPTION
**Pull request by mcepl**
This is just rebasing of #15, #16, and #17 on the top of the current master.

I have been running this for the past couple of weeks on the top of vis, and it doesn't seem to break anything. I haven’t measured the speed difference, but even with large XML files (Bible text, approx. 15MB) the editor was very swift.

### CODE REVIEW

**Comment by orbitalquark** [comment]
Thanks, I'll take a look when I have some time.

**Comment by orbitalquark** [comment]
Thanks again for submitting this. To be clear, the lexers were already fast, as there was no expensive tag test to highlight '=' and number attribute values -- it could be a bit sloppy.

This PR adds an inexpensive postfix (look-ahead) tag test. The commented out test was a prefix test with look-behind.

After experimentation, there are a couple issues I have with this change.

1. Normally, Scintillua matches entities with the closing delimiter as optional (strings, block comments, etc.). This change goes against that. Something like `<div class="foo"` will not highlight properly until the closing `>` is added. You won't see this if your editor automatically adds a closing '>' when typing '<'.
2. Some editors start lexing at the start of a line, so building on the point above, a multi-line tag will never highlight attributes properly, even after typing a closing '>'. For example:

```
<div
class="foo"
style="float: left;"
```

Typing a '>' on the 'style' line will highlight only that line and leave the 'class' line alone, and typing a '>' after the 'style' line will not highlight either attribute line.

The first issue I could perhaps be okay with, as technically a tag is not valid until it is closed, but the second issue is more problematic, because we cannot assume an editor inserts a trailing '>' automatically, so Scintillua may not highlight a finished tag.

**Comment by mcepl** [comment]
I have no problem if you decide that you don’t want these changes (I am quite certain, that you understand intricacies of Scintillua lexers a way more than me and @moesasji combined), but then it would be probably better to make the decision and close all those PRs.

**Comment by orbitalquark** [comment]
Okay, I will close the PRs then.

**Pull request closed without merging**
